version: 0.2
phases:
  install:
    runtime-versions: 
      python: 3.8
    commands:
      - cd src/ 
      - pip3 install virtualenv
      - virtualenv env
      - . env/bin/activate
      - pip3 install -r requirements.txt
      - cd ..
      - sam build 
      - sam package --s3-bucket builds-lambda-test --output-template-file outputTemplate.yml
      # --s3-prefix createsms_usbankdemo This is a folder
artifacts:
  type: zip
  files:
    - template.yml 
    - outputTemplate.yml