version: 0.2
phases:
  install:
    runtime-versions: 
      python: 3.8
    commands:
      - cd src/ 
      - zip CreateSMS_USBankDemo.zip index.py
      - aws s3 cp CreateSMS_USBankDemo.zip s3://lambda-functions-cloudformation/CreateSMS_USBankDemo.zip
      - rm -r CreateSMS_USBankDemo.zip
      - pip3 install virtualenv
      - virtualenv env
      - . env/bin/activate
      - pip3 install -r requirements.txt
      - cd ..
      - sam build 
      - sam package --s3-bucket usbankdemobuilds --s3-prefix createsms_usbankdemo --output-template-file outputTemplate.yml
artifacts:
  type: zip
  files:
    - template.yml 
    - outputTemplate.yml