AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SMS Creation for US Bank
Resources:
 SampleFunction:
  Type: AWS::Serverless::Function
  Properties:
   Handler: index.lambda_handler
   Runtime: python3.8
   FunctionName: CreateSMS_USBankDemo2
   CodeUri: ./src/ #Directory the source file is