AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SMS Creation for US Bank
Resources:
 Lambda_build_test:
  Type: AWS::Serverless::Function
  Properties:
   Handler: lambda_function.lambda_handler
   Runtime: python3.8
   FunctionName: Lambda_Build_test
   CodeUri: ./src/ #Directory the source file is