version: 0.2
phases:
  install:
    runtime-versions: 
      python: 3.8
    commands:
      - cd src/
      - zip CreateSMS_USBankDemo.zip lambda_function.py
      - aws s3 cp CreateSMS_USBankDemo.zip s3://builds-lambda-test/lambda_test_build.zip
      - rm -r CreateSMS_USBankDemo.zip 
      - pip3 install virtualenv
      - virtualenv env
      - . env/bin/activate
      - pip3 install -r requirements.txt
  post_build:
    commands:
      - cd ..
      - python3 -m unittest discover -v
artifacts:
  type: zip
  files:
    - template.yml 
    - unittestOutputTemplate.yml